# Generated by Django 5.1.1 on 2024-09-12 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todo_language_todo_linenos_todo_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='code',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
